// Write src/shader.ts from tandem.wgsl and the entry point files, and src/stream_wasm.ts from
// src/stream.wat, so the package needs no file loading at runtime. The entry points are
// appended because they use the first file's names.
// Usage: deno run --allow-read --allow-write tools/embed.ts
import wabtInit from "npm:wabt@1.0.39";

const FILES = ["tandem.wgsl", "tandem_f32.wgsl", "tandem_derived.wgsl"];
const read = (name: string) => Deno.readTextFile(new URL(`../${name}`, import.meta.url));
const write = (name: string, text: string) =>
  Deno.writeTextFile(new URL(`../src/${name}`, import.meta.url), text);

const wgsl = (await Promise.all(FILES.map(read))).join("\n");
await write(
  "shader.ts",
  `// Generated by tools/embed.ts from ${FILES.join(", ")}. Do not edit.\n` +
    `export const SHADER = ${JSON.stringify(wgsl)};\n`,
);

const wabt = await wabtInit();
const module = wabt.parseWat("stream.wat", await read("src/stream.wat"), { simd: true });
module.validate();
const wasm = module.toBinary({}).buffer;
await write(
  "stream_wasm.ts",
  "// Generated by tools/embed.ts from src/stream.wat. Do not edit.\n" +
    `export const WASM = Uint8Array.from(atob("${
      btoa(String.fromCharCode(...wasm))
    }"), (c) => c.charCodeAt(0));\n`,
);
