// Write src/shader.ts from tandem.wgsl and tandem_f32.wgsl, so the package needs no file
// loading at runtime. The f32 entry point is appended because it uses the first file's names.
// Usage: deno run --allow-read --allow-write tools/embed.ts
const read = (name: string) => Deno.readTextFile(new URL(`../${name}`, import.meta.url));
const wgsl = `${await read("tandem.wgsl")}\n${await read("tandem_f32.wgsl")}`;
const out =
  `// Generated by tools/embed.ts from tandem.wgsl and tandem_f32.wgsl. Do not edit.\nexport const SHADER = ${
    JSON.stringify(wgsl)
  };\n`;
await Deno.writeTextFile(new URL("../src/shader.ts", import.meta.url), out);
