// Write src/shader.ts from tandem.wgsl and the entry point files, so the package needs no file
// loading at runtime. The entry points are appended because they use the first file's names.
// Usage: deno run --allow-read --allow-write tools/embed.ts
const FILES = ["tandem.wgsl", "tandem_f32.wgsl", "tandem_derived.wgsl"];
const read = (name: string) => Deno.readTextFile(new URL(`../${name}`, import.meta.url));
const wgsl = (await Promise.all(FILES.map(read))).join("\n");
const out = `// Generated by tools/embed.ts from ${
  FILES.join(", ")
}. Do not edit.\nexport const SHADER = ${JSON.stringify(wgsl)};\n`;
await Deno.writeTextFile(new URL("../src/shader.ts", import.meta.url), out);
