// Write src/zig_tables.ts, the Float64 normal ziggurat tables, from the spec's table file
// (Appendix A, "Normals"). Its SHA-256 must match the value the spec publishes, so a changed
// table file fails here instead of changing the normals.
// Usage: deno run --allow-read --allow-write tools/gen_zig_tables.ts ../tandem-spec/tables/normal_f64_zig1024.json
import { createHash } from "node:crypto";

const SHA256 = "8b961dd46a2582b953bd8780138edb0ad712e3d243a366a123ffc8978d0a33ab";
const LAYERS = 1024;

/** A canonical hexadecimal float of a normal double, exactly: the 53-bit integer mantissa and
 * the power of two are both exact, so is their product. */
function hexfloat(s: string): number {
  const m = /^0x1\.([0-9a-f]{13})p([+-]\d+)$/.exec(s);
  if (!m) throw new Error(`not a canonical hexadecimal float: ${s}`);
  return (2 ** 52 + parseInt(m[1], 16)) * 2 ** (Number(m[2]) - 52);
}

const path = Deno.args[0];
if (!path) throw new Error("usage: gen_zig_tables.ts <normal_f64_zig1024.json>");
const data = await Deno.readFile(path);
const digest = createHash("sha256").update(data).digest("hex");
if (digest !== SHA256) throw new Error(`${path}: SHA-256 ${digest}, expected ${SHA256}`);
const t = JSON.parse(new TextDecoder().decode(data));
if (
  t.layers !== LAYERS || t.W.length !== LAYERS || t.K.length !== LAYERS ||
  t.Y.length !== LAYERS + 1
) {
  throw new Error("unexpected table sizes");
}
// K is below 2^53, so a double holds it exactly. JSON.parse would round a larger one.
if (!t.K.every((k: number) => Number.isSafeInteger(k))) throw new Error("K above 2^53");

const rows = (values: number[]) => {
  const lines = [];
  for (let i = 0; i < values.length; i += 4) {
    lines.push("  " + values.slice(i, i + 4).map(String).join(", ") + ",");
  }
  return lines.join("\n");
};

const out = `// Generated by tools/gen_zig_tables.ts from the spec's tables/normal_f64_zig1024.json
// (SHA-256 ${SHA256}). Do not edit.
// The Float64 normal ziggurat of Appendix A with ${LAYERS} layers: widths W, thresholds K and
// heights Y. Every value is the exact double of the spec's hexadecimal float.

export const ZIG_R = ${hexfloat(t.R)};

export const ZIG_W = Float64Array.of(
${rows(t.W.map(hexfloat))}
);

export const ZIG_K = Float64Array.of(
${rows(t.K)}
);

export const ZIG_Y = Float64Array.of(
${rows(t.Y.map(hexfloat))}
);
`;
await Deno.writeTextFile(new URL("../src/zig_tables.ts", import.meta.url), out);
